### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by lokal-profil** [Wikimedia-Sverige/tastydata#1]
1. Footer should stick to bottom also after scrolling (on tablets).
2. Footer should always be below menu (currently it is sometimes behind). Ideally with some minimum clearance. 
3. Footer should be full width rather than linebreaking after column one.
4. Footer should be visually similar to menu (same bg-color, white text and links) possibly with the exception of underlined links.

**Comment by lokal-profil** [comment]
4: Is achieved by adding the following to `main.css`

``` css
.footer {
    color: white;
}
.footer a {
    color: white;
    text-decoration: underline;
}
```

And adding `.footer` after `.menu` in the generated css.

This can however not be done until 2. has been addressed.
